services:
    database_service:
        class:        AppBundle\Service\DatabaseService
        arguments:    [%database_host%, %database_port%, %database_name%]
    cache_service:
        class:        AppBundle\Service\CacheService
        arguments:    [@cache_connection]
    cache_connection:
        class:        Predis\Client
        arguments:
          - host: %cache_host%
          - port: %cache_port%
          - prefix: %cache_prefix